s = str('это строка')
print(s.capitalize())
print(s.casefold())
print(s.center(1))
print(s.count(' '))
print(s.encode())
print(s.endswith('j'))
print(s.find('о'))
print(s.format())
print(s.format_map())
print(s.index(5))
print(s.zfill())
s.lower()
